const splat2Maps = [
    "The Reef",
    "Musselforge Fitness",
    "Starfish Mainstage",
    "Humpback Pump Track",
    "Inkblot Art Academy",
    "Sturgeon Shipyard",
    "Moray Towers (Splatoon 2)",
    "Port Mackerel",
    "Manta Maria",
    "Kelp Dome (Splatoon 2)",
    "Snapper Canal",
    "Blackbelly Skatepark (Splatoon 2)",
    "MakoMart",
    "Walleye Warehouse",
    "Shellendorf Institute",
    "Arowana Mall (Splatoon 2)",
    "Goby Arena",
    "Piranha Pit (Splatoon 2)",
    "Camp Triggerfish (Splatoon 2)",
    "Wahoo World",
    "New Albacore Hotel",
    "Ancho-V Games (Splatoon 2)",
    "Skipper Pavilion",
    "Old Urchin Underpass",
    "New Urchin Underpass",
    "Saltspray Rig",
    "Arowana Mall (Splatoon 1)",
    "Blackbelly Skatepark (Splatoon 1)",
    "Port Mackerel (Splatoon 1)",
    "Bluefin Depot",
    "Moray Towers (Splatoon 1)",
    "Camp Triggerfish (Splatoon 1)",
    "Flounder Heights",
    "Hammerhead Bridge",
    "Museum d'Alfonsino",
    "Mahi-Mahi Resort",
    "Piranha Pit (Splatoon 1)",
    "Ancho-V Games (Splatoon 1)"
];

const splat3Maps = [
    "Scorch Gorge",
    "Eeltail Alley",
    "Hagglefish Market",
    "Undertow Spillway",
    "Mincemeat Metalworks",
    "Hammerhead Bridge",
    "Museum d'Alfonsino",
    "Mahi-Mahi Resort",
    "Inkblot Art Academy",
    "Sturgeon Shipyard",
    "MakoMart",
    "Wahoo World",
    "Flounder Heights",
    "Brinewater Springs",
    "Manta Maria",
    "Um'ami Ruins"
];
