const splat2Maps = [
    "The Reef",
    "Musselforge Fitness",
    "Starfish Mainstage",
    "Humpback Pump Track",
    "Inkblot Art Academy",
    "Sturgeon Shipyard",
    "Moray Towers",
    "Port Mackerel",
    "Manta Maria",
    "Kelp Dome",
    "Snapper Canal",
    "Blackbelly Skatepark",
    "MakoMart",
    "Walleye Warehouse",
    "Shellendorf Institute",
    "Arowana Mall",
    "Goby Arena",
    "Piranha Pit",
    "Camp Triggerfish",
    "Wahoo World",
    "New Albacore Hotel",
    "Ancho-V Games",
    "Skipper Pavilion"
];

const splat3Maps = [
    "Scorch Gorge",
    "Eeltail Alley",
    "Hagglefish Market",
    "Undertow Spillway",
    "Mincemeat Metalworks",
    "Hammerhead Bridge",
    "Museum d'Alfonsino",
    "Mahi-Mahi Resort",
    "Inkblot Art Academy",
    "Sturgeon Shipyard",
    "MakoMart",
    "Wahoo World",
    "Flounder Heights",
    "Brinewater Springs"
];
